[package]
name = "ctl"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.8", features = ["derive"] }
concat-idents = "1.1.5"
derive_more = "0.99.17"
enum-as-inner = "0.6.0"
indexmap = "2.0.0"
